name: fintech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  gap: ^3.0.1
  get_it: ^9.1.0
  hydrated_bloc: ^10.1.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/icons/
    - assets/translations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
